version: '3'
services:
    postgis:
        image: "postgis/postgis:12-3.0-alpine"
        env_file:
            - database.env
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}
